"""
Django settings for campaign_project project.

Generated by 'django-admin startproject' using Django 5.2.9.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret")
DEBUG = True
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'corsheaders',
    'onboarding',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "campaign_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "campaign_project.wsgi.application"

TEMPLATES[0]["DIRS"] = [BASE_DIR / "frontend_dist"]

IS_RAILWAY_PROD = os.environ.get('DATABASE_URL') is not None

if IS_RAILWAY_PROD:
    # Production Settings (PostgreSQL via Railway)
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

    MEDIA_ROOT = "/app/media"
    MEDIA_URL = "/media/"

else:
    # Local Development Settings (SQLite)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

    MEDIA_ROOT = BASE_DIR / "media"
    MEDIA_URL = "/media/"

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STATICFILES_DIRS = [
    BASE_DIR / "frontend_dist",  # so /assets/* is found
]


# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    "https://ipo-production-1f64.up.railway.app",
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    'https://go.thetrumpet.app',
    'https://thetrumpet.app',
    'https://www.thetrumpet.app',
]

# Allow additional trusted origins from environment variable (comma-separated)
additional_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if additional_origins:
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in additional_origins.split(",")])

# Allow CSRF cookie to be sent from any origin in development
if not IS_RAILWAY_PROD:
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False
else:
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True

# Media Settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# GHL (GoHighLevel) API Settings
GHL_API_TOKEN = os.environ.get('GHL_API_TOKEN', '')  # Agency-level PIT for location creation
GHL_COMPANY_ID = os.environ.get('GHL_COMPANY_ID', '')
GHL_SNAPSHOT_ID = os.environ.get('GHL_SNAPSHOT_ID', '')
# Location-specific PIT for contact creation (can be set per location or use default)
GHL_LOCATION_API_TOKEN = os.environ.get('GHL_LOCATION_API_TOKEN', '')  # Location-specific PIT for contacts
GHL_OTP_LOCATION_ID = os.environ.get('GHL_OTP_LOCATION_ID', 'DAl4SWtHOBVUw1E9EYPb')  # Static location ID for OTP contacts
GHL_APP_OTP_FIELD_ID = os.environ.get('GHL_APP_OTP_FIELD_ID', '03MbSDQPsw1nvfCjU8At')  # Custom field ID for app_otp
GHL_API_BASE_URL = 'https://services.leadconnectorhq.com'
BACKUP_OTP_CODE = os.environ.get('BACKUP_OTP_CODE')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
