# Generated by Django 5.2.9 on 2025-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CampaignSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "template_style",
                    models.CharField(
                        choices=[
                            ("modern", "Modern"),
                            ("traditional", "Traditional"),
                            ("bold", "Bold"),
                        ],
                        default="modern",
                        max_length=20,
                    ),
                ),
                ("primary_color", models.CharField(default="#0d6efd", max_length=7)),
                ("secondary_color", models.CharField(default="#6c757d", max_length=7)),
                ("pillar_1", models.CharField(max_length=100)),
                ("pillar_2", models.CharField(max_length=100)),
                ("pillar_3", models.CharField(max_length=100)),
                ("bio_text", models.TextField(max_length=1000)),
                ("donation_url", models.URLField(blank=True, null=True)),
                (
                    "event_calendar_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("headshot", models.ImageField(upload_to="headshots/")),
                (
                    "action_shot_1",
                    models.ImageField(blank=True, null=True, upload_to="action_shots/"),
                ),
                (
                    "action_shot_2",
                    models.ImageField(blank=True, null=True, upload_to="action_shots/"),
                ),
                (
                    "action_shot_3",
                    models.ImageField(blank=True, null=True, upload_to="action_shots/"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("otp_code", models.CharField(blank=True, max_length=6, null=True)),
                ("otp_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
