# Generated by Django 4.2.7 on 2025-12-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsubmission",
            name="pillar_1_desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="pillar_2_desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="pillar_3_desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
