# Generated by Django 5.2.9 on 2025-12-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0005_campaignsubmission_election_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsubmission",
            name="position_running_for",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="tag_line",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
