# Generated by Django 5.2.9 on 2025-12-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0006_campaignsubmission_position_running_for_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignsubmission",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
