# Generated by Django 5.2.9 on 2025-12-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0007_alter_campaignsubmission_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsubmission",
            name="background_picture",
            field=models.ImageField(blank=True, null=True, upload_to="backgrounds/"),
        ),
    ]
