# Generated by Django 5.2.9 on 2026-01-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0008_campaignsubmission_background_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignsubmission",
            name="headshot",
            field=models.ImageField(blank=True, null=True, upload_to="headshots/"),
        ),
    ]
