# Generated by Django 5.2.9 on 2025-12-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0008_campaignsubmission_background_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsubmission",
            name="campaign_subtype",
            field=models.CharField(
                blank=True,
                choices=[("campaign", "Campaign in a Box"), ("election", "Election")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="organization_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="organization_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("church", "Church"),
                    ("charity", "Charity"),
                    ("eda", "Economic Development Association"),
                    ("ca", "Community Association"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="owner_photo",
            field=models.ImageField(blank=True, null=True, upload_to="owners/"),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="preferred_template",
            field=models.CharField(
                choices=[
                    ("modern", "Modern"),
                    ("traditional", "Traditional"),
                    ("bold", "Bold"),
                ],
                default="modern",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="sales_team_photo",
            field=models.ImageField(blank=True, null=True, upload_to="sales_teams/"),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="submission_type",
            field=models.CharField(
                choices=[("organization", "Organization"), ("campaign", "Campaign")],
                default="campaign",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="template_bold_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="template_modern_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="campaignsubmission",
            name="template_traditional_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
