# Generated by Django 5.2.9 on 2026-01-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0009_alter_campaignsubmission_headshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsubmission",
            name="ghl_location_id",
            field=models.CharField(
                blank=True,
                help_text="GoHighLevel Location/Sub-Account ID",
                max_length=100,
                null=True,
            ),
        ),
    ]
