# Generated by Django 5.2.9 on 2025-12-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0009_campaignsubmission_campaign_subtype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "template_style",
                    models.CharField(
                        choices=[
                            ("modern", "Modern"),
                            ("traditional", "Traditional"),
                            ("bold", "Bold"),
                        ],
                        default="modern",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_template",
                    models.CharField(
                        choices=[
                            ("modern", "Modern"),
                            ("traditional", "Traditional"),
                            ("bold", "Bold"),
                        ],
                        default="modern",
                        max_length=20,
                    ),
                ),
                ("primary_color", models.CharField(default="#0d6efd", max_length=7)),
                ("secondary_color", models.CharField(default="#6c757d", max_length=7)),
                ("bio_text", models.TextField(max_length=1000)),
                ("tag_line", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "background_picture",
                    models.ImageField(blank=True, null=True, upload_to="backgrounds/"),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "template_modern_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "template_traditional_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "template_bold_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "custom_slug",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_password_protected", models.BooleanField(default=False)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                ("otp_code", models.CharField(blank=True, max_length=6, null=True)),
                ("otp_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization_subtype",
                    models.CharField(
                        choices=[
                            ("church", "Church"),
                            ("charity", "Charity"),
                            ("eda", "Economic Development Association"),
                            ("ca", "Community Association"),
                        ],
                        max_length=20,
                    ),
                ),
                ("organization_name", models.CharField(max_length=200)),
                ("logo", models.ImageField(upload_to="logos/")),
                ("owner_photo", models.ImageField(upload_to="owners/")),
                (
                    "sales_team_photo",
                    models.ImageField(blank=True, null=True, upload_to="sales_teams/"),
                ),
                ("service_1", models.CharField(max_length=200)),
                ("service_1_desc", models.TextField(blank=True, null=True)),
                ("service_2", models.CharField(max_length=200)),
                ("service_2_desc", models.TextField(blank=True, null=True)),
                ("service_3", models.CharField(max_length=200)),
                ("service_3_desc", models.TextField(blank=True, null=True)),
                (
                    "service_image_1",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_images/"
                    ),
                ),
                (
                    "service_image_2",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_images/"
                    ),
                ),
                (
                    "service_image_3",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_images/"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="campaignsubmission",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="campaignsubmission",
            name="organization_name",
        ),
        migrations.RemoveField(
            model_name="campaignsubmission",
            name="organization_subtype",
        ),
        migrations.RemoveField(
            model_name="campaignsubmission",
            name="owner_photo",
        ),
        migrations.RemoveField(
            model_name="campaignsubmission",
            name="sales_team_photo",
        ),
        migrations.RemoveField(
            model_name="campaignsubmission",
            name="submission_type",
        ),
        migrations.AlterField(
            model_name="campaignsubmission",
            name="campaign_subtype",
            field=models.CharField(
                choices=[("campaign", "Campaign in a Box"), ("election", "Election")],
                default="election",
                max_length=20,
            ),
        ),
    ]
