# Generated by Django 5.2.9 on 2026-01-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0010_campaignsubmission_ghl_location_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsubmission",
            name="ghl_contact_id",
            field=models.CharField(
                blank=True,
                help_text="GoHighLevel Contact ID for OTP verification",
                max_length=100,
                null=True,
            ),
        ),
    ]
